version: "3.7"

services:
    database_dbead:
        image: postgres
        container_name: database_dbead
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASS=docker
            - POSTGRES_DB=backendead
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: backendead
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app

volumes:
    pgdata:
        driver: local
